// GENERATED by tools/gen-theme.mjs — do not edit.
// Source of truth: tools/styleguide.manifest.json (OKLCH). Regenerate with
// `node tools/gen-theme.mjs`; the styleguide gate regen-diffs this file, so a
// hand edit here is a red gate, not a design change.

export const palettes = {
  dark: {
    canvas: '#0b0e10',
    surface: '#16191b',
    edge: '#2f3337',
    ink: '#e5e8eb',
    'ink-muted': '#9fa6aa',
    accent: '#43d5dc',
    danger: '#f97770',
    success: '#68ca80',
  },
  light: {
    canvas: '#f3f5f7',
    surface: '#e5e8eb',
    edge: '#c0c5c9',
    ink: '#1d2226',
    'ink-muted': '#555c61',
    accent: '#03696e',
    danger: '#b71824',
    success: '#067132',
  },
} as const

export type ResolvedThemeName = keyof typeof palettes
export type TokenName = keyof (typeof palettes)['dark']
/** One theme's token set, widened to plain strings for style factories. */
export type Palette = Readonly<Record<TokenName, string>>

export const fontWeight = {
  bold: '700',
  medium: '500',
  normal: '400',
  semibold: '600',
} as const

export const typeScale = {
  '2xl': { fontSize: 24, lineHeight: 32 },
  base: { fontSize: 16, lineHeight: 24 },
  lg: { fontSize: 18, lineHeight: 28 },
  sm: { fontSize: 14, lineHeight: 20 },
  xl: { fontSize: 20, lineHeight: 28 },
  xs: { fontSize: 12, lineHeight: 16 },
} as const

export const radius = {
  lg: 8,
  md: 6,
  sm: 4,
} as const

/** Spacing base unit (dp). Multiply it — never hand-write raw offsets. */
export const spacing = 4
