#!/usr/bin/env node
// tools/gen-theme.mjs — emit the committed token module from the styleguide manifest.
//
// tools/styleguide.manifest.json is the OKLCH source of truth; this script converts
// every theme's tokens OKLCH -> linear sRGB -> gamma-encoded hex (tools/lib/oklch.mjs,
// the same math the styleguide gate uses to COMPUTE contrast) and writes
// apps/mobile/src/theme/tokens.gen.ts: the palettes plus the fontWeight/text/radius/
// spacing scales from `families`. The output is deterministic and byte-stable (token
// order comes from the manifest's canonical `tokens` array, family keys are sorted,
// formatting is fixed) so the styleguide gate can regen-diff the committed file.
//
// An out-of-gamut OKLCH token is a hard FAIL, never a silent clamp: the platform
// would gamut-map it on screen, so every computed contrast number would describe a
// color nobody sees. Retune the manifest value instead.
// SOURCE: CSS Color 4 OKLCH->sRGB reference conversion + sRGB transfer function
// https://www.w3.org/TR/css-color-4/#color-conversion-code
//   usage: node tools/gen-theme.mjs           (regenerate the committed file)
//          node tools/gen-theme.mjs --check   (exit 2 when the committed file drifts)
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { contrastRatio, inSrgbGamut, oklchToLinearSrgb, relativeLuminance } from './lib/oklch.mjs'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const MANIFEST = new URL('./styleguide.manifest.json', import.meta.url)
const OUT_REL = 'apps/mobile/src/theme/tokens.gen.ts'

// Linear-light channel -> 8-bit gamma-encoded sRGB (the CSS Color 4 transfer
// function), after the gamut check has guaranteed v in [0,1] (± float slop).
function channelToByte(v) {
  const clamped = Math.min(1, Math.max(0, v))
  const encoded = clamped <= 0.0031308 ? 12.92 * clamped : 1.055 * clamped ** (1 / 2.4) - 0.055
  return Math.round(encoded * 255)
}

export function oklchToHex({ l, c, h }) {
  const linear = oklchToLinearSrgb(l, c, h)
  if (!inSrgbGamut(linear)) {
    throw new Error(`oklch(${l} ${c} ${h}) is outside the sRGB gamut — retune the manifest value`)
  }
  const bytes = [linear.r, linear.g, linear.b].map(channelToByte)
  return `#${bytes.map((b) => b.toString(16).padStart(2, '0')).join('')}`
}

// Quote a key only when it is not a valid bare TS identifier ('ink-muted', '2xl').
function tsKey(name) {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`
}

// Regeneration is FAIL-CLOSED on the manifest's own contract: every declared
// contrast pair must clear its minimum in every theme BEFORE any token is
// emitted, so a retuned value that breaks readability can never reach the
// committed module (the styleguide gate re-asserts the same numbers in the
// validate chain — same math, two moments).
export function assertContrast(manifest) {
  const failures = []
  for (const [theme, { tokens }] of Object.entries(manifest.themes)) {
    for (const pair of manifest.contrast) {
      const fg = tokens[pair.fg]
      const bg = tokens[pair.bg]
      const ratio = contrastRatio(
        relativeLuminance(oklchToLinearSrgb(fg.l, fg.c, fg.h)),
        relativeLuminance(oklchToLinearSrgb(bg.l, bg.c, bg.h)),
      )
      if (ratio < pair.min) {
        failures.push(`${theme}: ${pair.fg}/${pair.bg} = ${ratio.toFixed(2)} < ${pair.min}`)
      }
    }
  }
  if (failures.length > 0) {
    throw new Error(`contrast contract violated:\n  ${failures.join('\n  ')}`)
  }
}

export function renderTokensModule(manifest) {
  assertContrast(manifest)
  const themeNames = Object.keys(manifest.themes).sort()
  const lines = [
    '// GENERATED by tools/gen-theme.mjs — do not edit.',
    '// Source of truth: tools/styleguide.manifest.json (OKLCH). Regenerate with',
    '// `node tools/gen-theme.mjs`; the styleguide gate regen-diffs this file, so a',
    '// hand edit here is a red gate, not a design change.',
    '',
    'export const palettes = {',
  ]
  for (const theme of themeNames) {
    const tokens = manifest.themes[theme].tokens
    // Completeness is structural: every theme carries exactly the canonical token
    // set, in the manifest's canonical order — a theme missing a token would paint
    // the other theme's value on its canvas.
    const declared = Object.keys(tokens).sort().join(',')
    const canonical = [...manifest.tokens].sort().join(',')
    if (declared !== canonical) {
      throw new Error(`theme "${theme}" tokens (${declared}) != manifest token set (${canonical})`)
    }
    lines.push(`  ${tsKey(theme)}: {`)
    for (const name of manifest.tokens) {
      lines.push(`    ${tsKey(name)}: '${oklchToHex(tokens[name])}',`)
    }
    lines.push('  },')
  }
  lines.push(
    '} as const',
    '',
    'export type ResolvedThemeName = keyof typeof palettes',
    `export type TokenName = keyof (typeof palettes)['${themeNames[0]}']`,
    "/** One theme's token set, widened to plain strings for style factories. */",
    'export type Palette = Readonly<Record<TokenName, string>>',
    '',
  )
  const families = manifest.families
  const sortedKeys = (obj) => Object.keys(obj).sort()
  lines.push('export const fontWeight = {')
  for (const k of sortedKeys(families.fontWeight)) {
    lines.push(`  ${tsKey(k)}: '${families.fontWeight[k]}',`)
  }
  lines.push('} as const', '', 'export const typeScale = {')
  for (const k of sortedKeys(families.text)) {
    const { fontSize, lineHeight } = families.text[k]
    lines.push(`  ${tsKey(k)}: { fontSize: ${fontSize}, lineHeight: ${lineHeight} },`)
  }
  lines.push('} as const', '', 'export const radius = {')
  for (const k of sortedKeys(families.radius)) {
    lines.push(`  ${tsKey(k)}: ${families.radius[k]},`)
  }
  lines.push(
    '} as const',
    '',
    '/** Spacing base unit (dp). Multiply it — never hand-write raw offsets. */',
    `export const spacing = ${families.spacing.unit}`,
    '',
  )
  return lines.join('\n')
}

// CLI wrapper — only when executed directly, so the styleguide gate (and tests)
// can import the pure render/convert functions without touching the filesystem.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'))
  const rendered = renderTokensModule(manifest)
  const outPath = `${ROOT}${OUT_REL}`

  if (process.argv.includes('--check')) {
    let current = null
    try {
      current = readFileSync(outPath, 'utf8')
    } catch {
      // missing counts as drift below
    }
    if (current !== rendered) {
      console.error(
        `GEN-THEME: DRIFT — ${OUT_REL} does not match the manifest; run: node tools/gen-theme.mjs`,
      )
      process.exit(2)
    }
    console.log(`GEN-THEME: CLEAN (${OUT_REL} matches the manifest)`)
  } else {
    writeFileSync(outPath, rendered)
    console.log(`GEN-THEME: wrote ${OUT_REL}`)
  }
}
